"""baseline battery schema

Revision ID: 0001
Revises: 
"""
import sqlalchemy as sa

from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_pairs',
    sa.Column('sentence_1', sa.Text(), nullable=False),
    sa.Column('sentence_2', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('subset_name', sa.String(length=16), nullable=False),
    sa.Column('label_quality', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('human_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_pairs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_pairs_generator_model'), ['generator_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_pairs_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_pairs_status'), ['status'], unique=False)

    op.create_table('comparisons',
    sa.Column('baseline', sa.Text(), nullable=False),
    sa.Column('modification', sa.Text(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('magnitude', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('evidence_sentence', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('human_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparisons_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_generator_model'), ['generator_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_status'), ['status'], unique=False)

    op.create_table('dpo_pairs',
    sa.Column('source_qa_id', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.JSON(), nullable=False),
    sa.Column('chosen', sa.JSON(), nullable=False),
    sa.Column('rejected', sa.JSON(), nullable=False),
    sa.Column('error_type', sa.String(length=40), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('human_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dpo_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dpo_pairs_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_dpo_pairs_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_dpo_pairs_generator_model'), ['generator_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_dpo_pairs_source_qa_id'), ['source_qa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dpo_pairs_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_dpo_pairs_status'), ['status'], unique=False)

    op.create_table('facts',
    sa.Column('material', sa.JSON(), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('property', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('triple', sa.JSON(), nullable=False),
    sa.Column('evidence_sentence', sa.Text(), nullable=False),
    sa.Column('label_quality', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('human_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_generator_model'), ['generator_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_status'), ['status'], unique=False)

    op.create_table('ideation',
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('ideas', sa.JSON(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('human_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_format', sa.String(length=32), nullable=False),
    sa.Column('polarity', sa.String(length=8), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=True),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('chemistry', sa.String(length=64), nullable=True),
    sa.Column('grounding', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ideation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ideation_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideation_generator_model'), ['generator_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideation_polarity'), ['polarity'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideation_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideation_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ideation_task_format'), ['task_format'], unique=False)

    op.create_table('materials',
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('formula', sa.String(length=128), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('material_id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_formula'), ['formula'], unique=False)

    op.create_table('negatives',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('flawed_element', sa.Text(), nullable=True),
    sa.Column('expert_response', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('linked_positive_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('human_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_format', sa.String(length=32), nullable=False),
    sa.Column('polarity', sa.String(length=8), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=True),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('chemistry', sa.String(length=64), nullable=True),
    sa.Column('grounding', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negatives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negatives_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_negatives_generator_model'), ['generator_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_negatives_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_negatives_polarity'), ['polarity'], unique=False)
        batch_op.create_index(batch_op.f('ix_negatives_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_negatives_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_negatives_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_negatives_task_format'), ['task_format'], unique=False)

    op.create_table('qa',
    sa.Column('answer_type', sa.String(length=8), nullable=False),
    sa.Column('phrase_type', sa.String(length=16), nullable=False),
    sa.Column('qid_linked_id', sa.String(length=64), nullable=True),
    sa.Column('closed_label', sa.String(length=16), nullable=True),
    sa.Column('triple', sa.JSON(), nullable=False),
    sa.Column('system', sa.Text(), nullable=True),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_ids', sa.JSON(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('generator_model', sa.String(length=128), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('human_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_format', sa.String(length=32), nullable=False),
    sa.Column('polarity', sa.String(length=8), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=True),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('chemistry', sa.String(length=64), nullable=True),
    sa.Column('grounding', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_generator_model'), ['generator_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_polarity'), ['polarity'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_task_format'), ['task_format'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_task_format'))
        batch_op.drop_index(batch_op.f('ix_qa_status'))
        batch_op.drop_index(batch_op.f('ix_qa_split'))
        batch_op.drop_index(batch_op.f('ix_qa_question_type'))
        batch_op.drop_index(batch_op.f('ix_qa_polarity'))
        batch_op.drop_index(batch_op.f('ix_qa_generator_model'))
        batch_op.drop_index(batch_op.f('ix_qa_component'))

    op.drop_table('qa')
    with op.batch_alter_table('negatives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negatives_task_format'))
        batch_op.drop_index(batch_op.f('ix_negatives_status'))
        batch_op.drop_index(batch_op.f('ix_negatives_split'))
        batch_op.drop_index(batch_op.f('ix_negatives_question_type'))
        batch_op.drop_index(batch_op.f('ix_negatives_polarity'))
        batch_op.drop_index(batch_op.f('ix_negatives_kind'))
        batch_op.drop_index(batch_op.f('ix_negatives_generator_model'))
        batch_op.drop_index(batch_op.f('ix_negatives_component'))

    op.drop_table('negatives')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_formula'))

    op.drop_table('materials')
    with op.batch_alter_table('ideation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ideation_task_format'))
        batch_op.drop_index(batch_op.f('ix_ideation_status'))
        batch_op.drop_index(batch_op.f('ix_ideation_split'))
        batch_op.drop_index(batch_op.f('ix_ideation_question_type'))
        batch_op.drop_index(batch_op.f('ix_ideation_polarity'))
        batch_op.drop_index(batch_op.f('ix_ideation_generator_model'))
        batch_op.drop_index(batch_op.f('ix_ideation_component'))

    op.drop_table('ideation')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_status'))
        batch_op.drop_index(batch_op.f('ix_facts_split'))
        batch_op.drop_index(batch_op.f('ix_facts_generator_model'))
        batch_op.drop_index(batch_op.f('ix_facts_component'))

    op.drop_table('facts')
    with op.batch_alter_table('dpo_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dpo_pairs_status'))
        batch_op.drop_index(batch_op.f('ix_dpo_pairs_split'))
        batch_op.drop_index(batch_op.f('ix_dpo_pairs_source_qa_id'))
        batch_op.drop_index(batch_op.f('ix_dpo_pairs_generator_model'))
        batch_op.drop_index(batch_op.f('ix_dpo_pairs_error_type'))
        batch_op.drop_index(batch_op.f('ix_dpo_pairs_component'))

    op.drop_table('dpo_pairs')
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparisons_status'))
        batch_op.drop_index(batch_op.f('ix_comparisons_split'))
        batch_op.drop_index(batch_op.f('ix_comparisons_generator_model'))
        batch_op.drop_index(batch_op.f('ix_comparisons_component'))

    op.drop_table('comparisons')
    with op.batch_alter_table('claim_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_pairs_status'))
        batch_op.drop_index(batch_op.f('ix_claim_pairs_split'))
        batch_op.drop_index(batch_op.f('ix_claim_pairs_generator_model'))
        batch_op.drop_index(batch_op.f('ix_claim_pairs_category'))

    op.drop_table('claim_pairs')
    # ### end Alembic commands ###
