"""add document blacklist fields

Revision ID: 1407c23cafbe
Revises: 7cfd4f5fe131
Create Date: 2026-09-14 18:20:10.853004
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1407c23cafbe'
down_revision: str | None = '7cfd4f5fe131'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blacklisted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('blacklist_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_blacklisted'), ['blacklisted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_blacklisted'))
        batch_op.drop_column('blacklist_reason')
        batch_op.drop_column('blacklisted')

    # ### end Alembic commands ###
