"""add llm_calls.reasoning_text

Revision ID: 7cfd4f5fe131
Revises: 2146bc16699b
Create Date: 2026-09-13 20:41:31.776428
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7cfd4f5fe131'
down_revision: str | None = '2146bc16699b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_column('reasoning_text')

    # ### end Alembic commands ###
